export const Texts: { [key: string]: string } = {
  loginText:
    'WIR SIND IHR ETABLIERTER & ZUVERLÄSSIGER STAHLHANDEL UND BIEGEBETRIEB FÜR DAS GESAMTE DEUTSCHE BUNDESGEBIET.',
  copyRight: 'TSG',
  privacy: 'Privacy Policy',
  terms: 'Terms of Use',
  cookies: 'Cookies',
  login: 'Login',
  usernameLabel: 'Nutzername',
  passwordLabel: 'Dein Passwort',
  usernamePlaceholder: 'Nutzername',
  passwordPlaceholder: 'Passwort',
  forgotPassword: 'Passwort Vergessen?',
  tourAnlegen: 'Tour Anlegen',
  tourPlaceHolder: 'e.g. Z01',
  tourName: 'Tour Name',
  cancel: 'Cancel',
  save: 'Save',
  move: 'Move',
  moveCardTitle: 'Move Card into Another Date',
  moveCardInputLabel: 'Choose the new date',
  delete: 'Delete',
  somethingWentWrong: 'Something went wrong',
};
