import IconGenerator from './iconGenerator';
import LogoSVG from 'assets/icons/logo.svg';
import PasswordHideSVG from 'assets/icons/password-hide.svg';
import PasswordShowSVG from 'assets/icons/password-show.svg';
import FacebookSVG from 'assets/icons/facebook.svg';
import TwitterSVG from 'assets/icons/twitter.svg';
import LinkedinSVG from 'assets/icons/linkedin.svg';
import InstagramSVG from 'assets/icons/instagram.svg';
import CopyRightSVG from 'assets/icons/copyright.svg';
import ArrowDownSVG from 'assets/icons/arrow-down.svg';
import AddSVG from 'assets/icons/add.svg';
import ArrowLeftSVG from 'assets/icons/arrow-left.svg';
import ArrowRightSVG from 'assets/icons/arrow-right.svg';
import LinkSVG from 'assets/icons/link.svg';
import CloseSVG from 'assets/icons/close.svg';
import FolderAddSVG from 'assets/icons/folder-add.svg';
import SwapSVG from 'assets/icons/swap.svg';
// exports
export const Logo = IconGenerator(LogoSVG);
export const PasswordHide = IconGenerator(PasswordHideSVG);
export const PasswordShow = IconGenerator(PasswordShowSVG);
export const Facebook = IconGenerator(FacebookSVG);
export const Twitter = IconGenerator(TwitterSVG);
export const Linkedin = IconGenerator(LinkedinSVG);
export const Instagram = IconGenerator(InstagramSVG);

export const CopyRight = IconGenerator(CopyRightSVG);
export const ArrowDown = IconGenerator(ArrowDownSVG);
export const Add = IconGenerator(AddSVG);
export const ArrowLeft = IconGenerator(ArrowLeftSVG);
export const ArrowRight = IconGenerator(ArrowRightSVG);
export const LinkIcon = IconGenerator(LinkSVG);
export const CloseIcon = IconGenerator(CloseSVG);
export const FolderAdd = IconGenerator(FolderAddSVG);
export const Swap = IconGenerator(SwapSVG);
